services:
  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - DEBUG=True
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app-network
    command: >
      bash -c "python manage.py migrate --noinput &&
               python manage.py collectstatic --noinput &&
               daphne config.asgi:application --bind 0.0.0.0 --port 8000"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    container_name: redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
